

CREATE TABLE `srampos_addon_bill_items_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`bill_id` int(11) NOT NULL  , 
	`bill_item_id` int(11) NOT NULL  , 
	`sale_item_id` int(11) NOT NULL  , 
	`addon_id` int(11) NOT NULL  , 
	`price` decimal(10,2) NOT NULL  , 
	`qty` decimal(10,2) NOT NULL  , 
	`subtotal` decimal(10,2) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_addon_sale_items_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`order_id` int(11) NOT NULL  , 
	`order_item_id` int(11) NOT NULL  , 
	`sale_item_id` int(11) NOT NULL  , 
	`split_id` varchar(100) COLLATE latin1_swedish_ci NOT NULL  , 
	`addon_id` int(11) NOT NULL  , 
	`price` decimal(25,2) NOT NULL  , 
	`qty` decimal(10,0) NOT NULL  , 
	`subtotal` decimal(25,2) NOT NULL  , 
	`image_path` varchar(200) COLLATE latin1_swedish_ci NOT NULL  , 
	`addon_name_img` text COLLATE latin1_swedish_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archival_tables`(
	`id` int(11) NOT NULL  auto_increment , 
	`archival_from_table` varchar(255) COLLATE latin1_swedish_ci NULL  , 
	`archival_to_table` varchar(255) COLLATE latin1_swedish_ci NULL  , 
	`active` tinyint(2) NULL  DEFAULT 0 , 
	PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_bbq_archival`(
	`id` int(11) NOT NULL  , 
	`reference_no` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`customer_id` bigint(20) NOT NULL  , 
	`warehouse_id` bigint(20) NOT NULL  , 
	`name` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`phone` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`email` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`number_of_adult` bigint(20) NOT NULL  , 
	`number_of_child` bigint(20) NOT NULL  , 
	`number_of_kids` bigint(20) NOT NULL  , 
	`bbq_set_id` bigint(20) NOT NULL  , 
	`adult_price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`child_price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`kids_price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`discount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`status` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`table_id` bigint(20) NOT NULL  , 
	`payment_status` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`cancel_status` tinyint(4) NOT NULL  , 
	`cancel_msg` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`cancel_by` bigint(20) NOT NULL  , 
	`created_by` bigint(20) NOT NULL  , 
	`created_on` date NOT NULL  , 
	`confirmed_by` int(11) NOT NULL  , 
	`order_request` tinyint(1) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_bbq_bil_items_archival`(
	`id` int(11) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`cover` bigint(20) NOT NULL  , 
	`price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`days` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`buyx` bigint(20) NOT NULL  , 
	`getx` bigint(20) NOT NULL  , 
	`discount_cover` bigint(20) NOT NULL  , 
	`discount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`tax_id` bigint(20) NOT NULL  , 
	`tax_type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`tax` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`subtotal` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`created` date NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_bil_items_archival`(
	`id` int(11) NOT NULL  , 
	`bil_id` int(11) unsigned NOT NULL  , 
	`recipe_id` int(11) unsigned NOT NULL  , 
	`recipe_code` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`option_id` int(11) NULL  , 
	`addon_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`addon_qty` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`net_unit_price` decimal(25,4) NOT NULL  , 
	`unit_price` decimal(25,6) NULL  , 
	`quantity` bigint(20) NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`item_tax` decimal(25,6) NULL  , 
	`tax_rate_id` int(11) NULL  , 
	`tax` varchar(55) COLLATE utf8_general_ci NULL  , 
	`tax_type` tinyint(1) NOT NULL  , 
	`service_charge_id` tinyint(4) NOT NULL  , 
	`service_charge_amount` decimal(16,2) NOT NULL  , 
	`discount` varchar(55) COLLATE utf8_general_ci NULL  , 
	`item_discount` decimal(25,6) NULL  , 
	`off_discount` decimal(25,6) NOT NULL  , 
	`input_discount` decimal(25,6) NOT NULL  , 
	`birthday_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`manual_item_discount_per_val` decimal(25,2) NOT NULL  , 
	`subtotal` decimal(25,6) NOT NULL  , 
	`serial_no` varchar(255) COLLATE utf8_general_ci NULL  , 
	`real_unit_price` decimal(25,6) NULL  , 
	`sale_item_id` int(11) NULL  , 
	`recipe_unit_id` int(11) NULL  , 
	`recipe_unit_code` varchar(255) COLLATE utf8_general_ci NULL  , 
	`unit_quantity` bigint(20) NOT NULL  , 
	`comment` text COLLATE utf8_general_ci NOT NULL  , 
	`comment_price` decimal(10,2) NOT NULL  , 
	`recipe_variant` varchar(200) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_variant_id` tinyint(4) NOT NULL  , 
	`customer_discount_val` varchar(40) COLLATE utf8_general_ci NULL  , 
	`grand_total` decimal(25,2) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_archive_bils_archival`(
	`id` int(11) NOT NULL  , 
	`bill_number` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`bill_sequence_number` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`bilgenerator_type` tinyint(4) NOT NULL  COMMENT '0-POS, 1-CUSTOMER' , 
	`consolidated` tinyint(4) NOT NULL  , 
	`sales_id` bigint(20) NOT NULL  , 
	`date` datetime NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`reference_no` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`delivery_person_id` bigint(20) NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`customer` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`biller_id` int(11) NOT NULL  , 
	`biller` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`bill_type` int(11) NOT NULL  , 
	`order_type` tinyint(4) NOT NULL  COMMENT '1->dine in,2->take away,3->door delivery,4->bbq' , 
	`note` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`staff_note` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`currencies_id` bigint(20) NOT NULL  , 
	`total` decimal(25,6) NOT NULL  , 
	`order_discount_id` varchar(20) COLLATE utf8_general_ci NULL  , 
	`total_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`birthday_discount` decimal(25,2) NOT NULL  , 
	`order_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`customer_discount_id` tinyint(5) NOT NULL  , 
	`customer_discount_amt` decimal(25,2) NOT NULL  , 
	`customer_discount_status` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`tax_id` int(11) NULL  , 
	`order_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`recipe_tax` decimal(25,6) NOT NULL  , 
	`total_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`tax_type` tinyint(1) NOT NULL  , 
	`service_charge_id` tinyint(4) NOT NULL  , 
	`service_charge_amount` decimal(16,2) NOT NULL  , 
	`shipping` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`grand_total` decimal(25,6) NOT NULL  , 
	`round_total` decimal(25,6) NOT NULL  , 
	`total_pay` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`balance` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`bil_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_term` tinyint(4) NULL  , 
	`due_date` date NULL  , 
	`created_by` int(11) NULL  , 
	`updated_by` int(11) NULL  , 
	`updated_at` timestamp NULL  , 
	`total_items` smallint(6) NULL  , 
	`paid_by` text COLLATE utf8_general_ci NOT NULL  , 
	`pos` tinyint(1) NOT NULL  DEFAULT 0 , 
	`paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`return_id` int(11) NULL  , 
	`surcharge` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`rounding` decimal(10,6) NULL  , 
	`api` tinyint(1) NULL  DEFAULT 0 , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`warehouse_id` tinyint(4) NOT NULL  , 
	`default_currency_code` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`default_currency_rate` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`table_whitelisted` tinyint(4) NOT NULL  DEFAULT 0 , 
	`discount_type` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`discount_val` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`unique_discount` tinyint(4) NOT NULL  , 
	`bbq_cover_discount` decimal(25,4) NOT NULL  , 
	`bbq_daywise_discount_id` tinyint(4) NOT NULL  , 
	`bbq_daywise_discount` decimal(10,2) NOT NULL  , 
	`order_status` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`action` tinyint(4) NOT NULL  COMMENT '1-edited,2-deleted' , 
	`delete_action` tinyint(4) NOT NULL  COMMENT '0-no,1-yes' , 
	`print_count` int(11) NOT NULL  , 
	`seats` int(11) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_kitchen_orders_archival`(
	`id` int(11) NOT NULL  , 
	`sale_id` bigint(20) NOT NULL  , 
	`waiter_id` bigint(20) NOT NULL  , 
	`chef_id` bigint(20) NOT NULL  , 
	`status` varchar(20) COLLATE latin1_swedish_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_order_items_archival`(
	`id` int(11) NOT NULL  , 
	`sale_id` int(11) unsigned NOT NULL  , 
	`item_status` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`kitchen_id` bigint(20) NOT NULL  , 
	`kitchen_type_id` bigint(20) NOT NULL  , 
	`recipe_id` int(11) unsigned NOT NULL  , 
	`recipe_code` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`option_id` int(11) NULL  , 
	`addon_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`addon_qty` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`buy_id` bigint(20) NOT NULL  , 
	`buy_quantity` bigint(20) NOT NULL  , 
	`get_item` bigint(20) NOT NULL  , 
	`get_quantity` bigint(20) NOT NULL  , 
	`total_get_quantity` bigint(20) NOT NULL  , 
	`net_unit_price` decimal(25,6) NOT NULL  , 
	`unit_price` decimal(25,6) NULL  , 
	`quantity` bigint(20) NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`order_item_cancel_id` tinyint(4) NOT NULL  COMMENT 'order cancelled update used id' , 
	`order_item_cancel_status` tinyint(1) NOT NULL  COMMENT '1->cancelled,0->not cancelled' , 
	`order_item_cancel_note` varchar(250) COLLATE utf8_general_ci NOT NULL  , 
	`item_tax` decimal(25,6) NULL  , 
	`tax_rate_id` int(11) NULL  , 
	`tax` varchar(55) COLLATE utf8_general_ci NULL  , 
	`discount` varchar(55) COLLATE utf8_general_ci NULL  , 
	`item_discount` decimal(25,6) NULL  , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`subtotal` decimal(25,6) NOT NULL  , 
	`serial_no` varchar(255) COLLATE utf8_general_ci NULL  , 
	`real_unit_price` decimal(25,6) NULL  , 
	`sale_item_id` int(11) NULL  , 
	`recipe_unit_id` int(11) NULL  , 
	`recipe_unit_code` varchar(10) COLLATE utf8_general_ci NULL  , 
	`unit_quantity` decimal(15,6) NOT NULL  , 
	`comment` varchar(255) COLLATE utf8_general_ci NULL  , 
	`comment_price` decimal(10,2) NOT NULL  , 
	`gst` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`time_started` datetime NOT NULL  , 
	`time_end` datetime NOT NULL  , 
	`escalation_one_time` datetime NOT NULL  , 
	`escalation_two_time` datetime NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`variant` varchar(200) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_variant_id` tinyint(4) NOT NULL  , 
	`stock_out_data` text COLLATE utf8_general_ci NOT NULL  , 
	`image_path` text COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name_img` text COLLATE utf8_general_ci NOT NULL  , 
	`addon_name_img` text COLLATE utf8_general_ci NOT NULL  , 
	`unwanted_ingredients` varchar(100) COLLATE utf8_general_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_orders_archival`(
	`id` int(11) NOT NULL  , 
	`order_type` tinyint(4) NOT NULL  , 
	`customer_request` tinyint(4) NOT NULL  , 
	`table_id` bigint(20) NOT NULL  , 
	`seats_id` bigint(20) NOT NULL  , 
	`split_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`order_status` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`order_from` enum('web','app') COLLATE utf8_general_ci NOT NULL  , 
	`date` datetime NOT NULL  COMMENT 'transaction date' , 
	`created_on` datetime NOT NULL  , 
	`reference_no` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`customer` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`biller_id` int(11) NOT NULL  , 
	`biller` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`total` decimal(25,6) NOT NULL  , 
	`recipe_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`order_discount_id` varchar(20) COLLATE utf8_general_ci NULL  , 
	`total_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`recipe_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_tax_id` int(11) NULL  , 
	`order_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`total_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`shipping` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`grand_total` decimal(25,6) NOT NULL  , 
	`sale_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_term` tinyint(4) NULL  , 
	`due_date` date NULL  , 
	`order_cancel_id` tinyint(4) NOT NULL  COMMENT 'order cancelled update used id' , 
	`order_cancel_status` tinyint(1) NOT NULL  COMMENT '1->cancelled,0->not cancelled' , 
	`order_cancel_note` varchar(250) COLLATE utf8_general_ci NOT NULL  , 
	`created_by` int(11) NULL  , 
	`updated_by` int(11) NULL  , 
	`updated_at` timestamp NULL  , 
	`total_items` smallint(6) NULL  , 
	`pos` tinyint(1) NOT NULL  DEFAULT 0 , 
	`paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`return_id` int(11) NULL  , 
	`surcharge` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`return_sale_ref` varchar(55) COLLATE utf8_general_ci NULL  , 
	`sale_id` int(11) NULL  , 
	`return_sale_total` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`rounding` decimal(10,6) NULL  , 
	`suspend_note` varchar(255) COLLATE utf8_general_ci NULL  , 
	`api` tinyint(1) NULL  DEFAULT 0 , 
	`shop` tinyint(1) NULL  DEFAULT 0 , 
	`address_id` int(11) NULL  , 
	`reserve_id` int(11) NULL  , 
	`hash` varchar(255) COLLATE utf8_general_ci NULL  , 
	`manual_payment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`table_whitelisted` tinyint(4) NOT NULL  , 
	`ordered_by` enum('steward','customer') COLLATE utf8_general_ci NOT NULL  , 
	`waiter_id` tinyint(4) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_payments_archival`(
	`id` int(11) NOT NULL  , 
	`action` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`date` datetime NULL  , 
	`paid_on` datetime NOT NULL  , 
	`sale_id` int(11) NULL  , 
	`bill_id` int(11) NOT NULL  , 
	`return_id` int(11) NULL  , 
	`purchase_id` int(11) NULL  , 
	`reference_no` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`transaction_id` varchar(50) COLLATE utf8_general_ci NULL  , 
	`paid_by` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`cheque_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_holder` varchar(25) COLLATE utf8_general_ci NULL  , 
	`cc_month` varchar(2) COLLATE utf8_general_ci NULL  , 
	`cc_year` varchar(4) COLLATE utf8_general_ci NULL  , 
	`cc_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`amount` decimal(25,6) NOT NULL  , 
	`amount_exchange` decimal(25,6) NOT NULL  , 
	`currency` varchar(3) COLLATE utf8_general_ci NULL  , 
	`created_by` int(11) NOT NULL  , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`note` text COLLATE utf8_general_ci NOT NULL  , 
	`type` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`sale_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` text COLLATE utf8_general_ci NOT NULL  , 
	`payment_note` text COLLATE utf8_general_ci NOT NULL  , 
	`pos_paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`pos_balance` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`approval_code` varchar(50) COLLATE utf8_general_ci NULL  , 
	`customer_payment_type` varchar(100) COLLATE utf8_general_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_restaurant_table_orders_archival`(
	`id` int(11) NOT NULL  , 
	`order_id` int(11) NOT NULL  , 
	`table_id` int(11) NOT NULL  , 
	`session_id` int(11) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_restaurant_table_sessions_archival`(
	`id` int(11) NOT NULL  , 
	`order_id` int(11) NOT NULL  , 
	`table_id` int(11) NOT NULL  , 
	`session_started` datetime NOT NULL  , 
	`session_end` datetime NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`split_id` varchar(255) COLLATE latin1_swedish_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_rough_tender_payments_archival`(
	`id` int(11) NOT NULL  , 
	`action` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`date` datetime NULL  , 
	`paid_on` datetime NOT NULL  , 
	`sale_id` int(11) NULL  , 
	`bill_id` int(11) NOT NULL  , 
	`return_id` int(11) NULL  , 
	`purchase_id` int(11) NULL  , 
	`reference_no` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`transaction_id` varchar(50) COLLATE utf8_general_ci NULL  , 
	`paid_by` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`cheque_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_holder` varchar(25) COLLATE utf8_general_ci NULL  , 
	`cc_month` varchar(2) COLLATE utf8_general_ci NULL  , 
	`cc_year` varchar(4) COLLATE utf8_general_ci NULL  , 
	`cc_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`amount` decimal(25,6) NOT NULL  , 
	`amount_exchange` decimal(25,6) NOT NULL  , 
	`currency` varchar(3) COLLATE utf8_general_ci NULL  , 
	`created_by` int(11) NOT NULL  , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`note` text COLLATE utf8_general_ci NOT NULL  , 
	`type` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`sale_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` text COLLATE utf8_general_ci NOT NULL  , 
	`payment_note` text COLLATE utf8_general_ci NOT NULL  , 
	`pos_paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`pos_balance` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`approval_code` varchar(50) COLLATE utf8_general_ci NULL  , 
	`customer_payment_type` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`bill_settled` tinyint(4) NOT NULL  COMMENT '0-No, 1-yes' , 
	`loyalty_points` int(11) NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_rough_tender_sale_currency_archival`(
	`id` int(11) NOT NULL  , 
	`sale_id` bigint(20) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`currency_id` int(11) NOT NULL  , 
	`currency_rate` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`paid_type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`amount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`created_on` date NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_sale_currency_archival`(
	`id` int(11) NOT NULL  , 
	`sale_id` bigint(20) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`currency_id` int(11) NOT NULL  , 
	`currency_rate` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`paid_type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`amount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`created_on` date NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_sale_items_archival`(
	`id` int(11) NOT NULL  , 
	`sale_id` int(11) unsigned NOT NULL  , 
	`bil_type` tinyint(4) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`recipe_id` int(11) unsigned NOT NULL  , 
	`recipe_code` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`item_status` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`option_id` int(11) NULL  , 
	`addon_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`addon_qty` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`net_unit_price` decimal(25,6) NOT NULL  , 
	`unit_price` decimal(25,6) NULL  , 
	`quantity` bigint(20) NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`item_tax` decimal(25,6) NULL  , 
	`tax_rate_id` int(11) NULL  , 
	`tax` varchar(55) COLLATE utf8_general_ci NULL  , 
	`discount` varchar(55) COLLATE utf8_general_ci NULL  , 
	`item_discount` decimal(25,6) NULL  , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`subtotal` decimal(25,6) NOT NULL  , 
	`serial_no` varchar(255) COLLATE utf8_general_ci NULL  , 
	`real_unit_price` decimal(25,6) NULL  , 
	`sale_item_id` int(11) NULL  , 
	`recipe_unit_id` int(11) NULL  , 
	`recipe_unit_code` varchar(10) COLLATE utf8_general_ci NULL  , 
	`unit_quantity` decimal(15,6) NOT NULL  , 
	`comment` varchar(255) COLLATE utf8_general_ci NULL  , 
	`comment_price` decimal(10,2) NOT NULL  , 
	`gst` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`recipe_variant_id` tinyint(4) NOT NULL  , 
	`variant` varchar(4) COLLATE utf8_general_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_archive_sales_archival`(
	`id` int(11) NOT NULL  , 
	`bilgenerator_type` tinyint(4) NOT NULL  COMMENT '0-POS, 1-CUSTOMER' , 
	`consolidated` tinyint(4) NOT NULL  , 
	`sales_type_id` tinyint(4) NOT NULL  , 
	`sales_split_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`sales_table_id` bigint(20) NOT NULL  , 
	`date` datetime NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`reference_no` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`delivery_person_id` bigint(20) NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`customer` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`biller_id` int(11) NOT NULL  , 
	`biller` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`total` decimal(25,6) NOT NULL  , 
	`recipe_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_discount_id` varchar(20) COLLATE utf8_general_ci NULL  , 
	`total_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_tax_id` int(11) NULL  , 
	`order_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`total_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`shipping` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`grand_total` decimal(25,6) NOT NULL  , 
	`sale_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_term` tinyint(4) NULL  , 
	`due_date` date NULL  , 
	`created_by` int(11) NULL  , 
	`updated_by` int(11) NULL  , 
	`updated_at` timestamp NULL  , 
	`total_items` smallint(6) NULL  , 
	`pos` tinyint(1) NOT NULL  DEFAULT 0 , 
	`paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`return_id` int(11) NULL  , 
	`surcharge` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`return_sale_ref` varchar(55) COLLATE utf8_general_ci NULL  , 
	`cancel_status` tinyint(4) NULL  DEFAULT 0 COMMENT '0->not cancel,1->cancel' , 
	`cancel_remarks` text COLLATE utf8_general_ci NOT NULL  , 
	`canceled_user_id` tinyint(4) NOT NULL  , 
	`return_sale_total` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`rounding` decimal(10,6) NULL  , 
	`suspend_note` varchar(255) COLLATE utf8_general_ci NULL  , 
	`api` tinyint(1) NULL  DEFAULT 0 , 
	`shop` tinyint(1) NULL  DEFAULT 0 , 
	`address_id` int(11) NULL  , 
	`reserve_id` int(11) NULL  , 
	`hash` varchar(255) COLLATE utf8_general_ci NULL  , 
	`manual_payment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`default_currency_code` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`default_currency_rate` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`table_whitelisted` tinyint(1) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_bbq_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`reference_no` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`bbq_menu_id` tinyint(4) NOT NULL  , 
	`customer_id` bigint(20) NOT NULL  , 
	`warehouse_id` bigint(20) NOT NULL  , 
	`name` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`phone` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`email` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`number_of_adult` bigint(20) NOT NULL  , 
	`number_of_child` bigint(20) NOT NULL  , 
	`number_of_kids` bigint(20) NOT NULL  , 
	`bbq_set_id` bigint(20) NOT NULL  , 
	`adult_price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`child_price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`kids_price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`discount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`status` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`table_id` bigint(20) NOT NULL  , 
	`payment_status` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`cancel_status` tinyint(4) NOT NULL  , 
	`cancel_msg` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`cancel_by` bigint(20) NOT NULL  , 
	`created_by` bigint(20) NOT NULL  , 
	`created_on` date NOT NULL  , 
	`confirmed_by` int(11) NOT NULL  , 
	`order_request` tinyint(1) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_bbq_bil_items_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`bil_id` bigint(20) NOT NULL  , 
	`type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`cover` bigint(20) NOT NULL  , 
	`price` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`days` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`buyx` bigint(20) NOT NULL  , 
	`getx` bigint(20) NOT NULL  , 
	`daywise_discount` decimal(10,2) NOT NULL  , 
	`daywise_discount_id` tinyint(4) NOT NULL  , 
	`discount_cover` bigint(20) NOT NULL  , 
	`discount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`tax_id` bigint(20) NOT NULL  , 
	`tax_type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`tax` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`subtotal` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`created` date NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';







CREATE TABLE `srampos_bil_items_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`bil_id` int(11) unsigned NOT NULL  , 
	`recipe_id` int(11) unsigned NOT NULL  , 
	`recipe_code` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`option_id` int(11) NULL  , 
	`addon_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`addon_qty` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`net_unit_price` decimal(25,4) NOT NULL  , 
	`unit_price` decimal(25,6) NULL  , 
	`quantity` bigint(20) NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`item_tax` decimal(25,6) NULL  , 
	`tax_rate_id` int(11) NULL  , 
	`tax` varchar(55) COLLATE utf8_general_ci NULL  , 
	`tax_type` tinyint(1) NOT NULL  , 
	`service_charge_id` tinyint(4) NOT NULL  , 
	`service_charge_amount` decimal(16,2) NOT NULL  , 
	`discount` varchar(55) COLLATE utf8_general_ci NULL  , 
	`item_discount` decimal(25,6) NULL  , 
	`off_discount` decimal(25,6) NOT NULL  , 
	`input_discount` decimal(25,6) NOT NULL  , 
	`birthday_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`manual_item_discount_per_val` decimal(25,2) NOT NULL  , 
	`subtotal` decimal(25,6) NOT NULL  , 
	`serial_no` varchar(255) COLLATE utf8_general_ci NULL  , 
	`real_unit_price` decimal(25,6) NULL  , 
	`sale_item_id` int(11) NULL  , 
	`recipe_unit_id` int(11) NULL  , 
	`recipe_unit_code` varchar(255) COLLATE utf8_general_ci NULL  , 
	`unit_quantity` bigint(20) NOT NULL  , 
	`comment` text COLLATE utf8_general_ci NOT NULL  , 
	`comment_price` decimal(10,2) NOT NULL  , 
	`recipe_variant` varchar(200) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_variant_id` tinyint(4) NOT NULL  , 
	`customer_discount_val` varchar(40) COLLATE utf8_general_ci NULL  , 
	`grand_total` decimal(25,2) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';




CREATE TABLE `srampos_bils_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`bill_number` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`bill_sequence_number` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`bilgenerator_type` tinyint(4) NOT NULL  COMMENT '0-POS, 1-CUSTOMER' , 
	`consolidated` tinyint(4) NOT NULL  , 
	`sales_id` bigint(20) NOT NULL  , 
	`date` datetime NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`reference_no` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`delivery_person_id` bigint(20) NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`customer` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`biller_id` int(11) NOT NULL  , 
	`biller` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`bill_type` int(11) NOT NULL  , 
	`order_type` tinyint(4) NOT NULL  COMMENT '1->dine in,2->take away,3->door delivery,4->bbq' , 
	`note` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`staff_note` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`currencies_id` bigint(20) NOT NULL  , 
	`total` decimal(25,6) NOT NULL  , 
	`order_discount_id` varchar(20) COLLATE utf8_general_ci NULL  , 
	`total_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`birthday_discount` decimal(25,2) NOT NULL  , 
	`order_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`customer_discount_id` tinyint(5) NOT NULL  , 
	`customer_discount_amt` decimal(25,2) NOT NULL  , 
	`customer_discount_status` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`tax_id` int(11) NULL  , 
	`order_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`recipe_tax` decimal(25,6) NOT NULL  , 
	`total_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`tax_type` tinyint(1) NOT NULL  , 
	`service_charge_id` tinyint(4) NOT NULL  , 
	`service_charge_amount` decimal(16,2) NOT NULL  , 
	`shipping` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`grand_total` decimal(25,6) NOT NULL  , 
	`round_total` decimal(25,6) NOT NULL  , 
	`total_pay` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`balance` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`bil_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_term` tinyint(4) NULL  , 
	`due_date` date NULL  , 
	`created_by` int(11) NULL  , 
	`updated_by` int(11) NULL  , 
	`updated_at` timestamp NULL  , 
	`total_items` smallint(6) NULL  , 
	`paid_by` text COLLATE utf8_general_ci NOT NULL  , 
	`pos` tinyint(1) NOT NULL  DEFAULT 0 , 
	`paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`return_id` int(11) NULL  , 
	`surcharge` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`rounding` decimal(10,6) NULL  , 
	`api` tinyint(1) NULL  DEFAULT 0 , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`warehouse_id` tinyint(4) NOT NULL  , 
	`default_currency_code` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`default_currency_rate` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`table_whitelisted` tinyint(4) NOT NULL  DEFAULT 0 , 
	`discount_type` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`discount_val` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`unique_discount` tinyint(4) NOT NULL  , 
	`bbq_cover_discount` decimal(25,4) NOT NULL  , 
	`bbq_daywise_discount_id` tinyint(4) NOT NULL  , 
	`bbq_daywise_discount` decimal(10,2) NOT NULL  , 
	`order_status` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`action` tinyint(4) NOT NULL  COMMENT '1-edited,2-deleted' , 
	`delete_action` tinyint(4) NOT NULL  COMMENT '0-no,1-yes' , 
	`print_count` int(11) NOT NULL  , 
	`seats` int(11) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';

CREATE TABLE `srampos_last_archival_process`(
	`id` int(11) NOT NULL  auto_increment , 
	`starttime` timestamp NOT NULL  DEFAULT '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP , 
	`endtime` timestamp NOT NULL  DEFAULT '0000-00-00 00:00:00' , 
	`status` varchar(255) NULL  , 
	`created_on` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP , 
	PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_notiy_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`msg` text COLLATE latin1_swedish_ci NOT NULL  , 
	`type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`table_id` bigint(20) NOT NULL  , 
	`user_id` bigint(20) NOT NULL  , 
	`role_id` bigint(20) NOT NULL  , 
	`to_user_id` bigint(20) NOT NULL  , 
	`order_item_id` bigint(20) NOT NULL  , 
	`warehouse_id` bigint(20) NOT NULL  , 
	`is_read` tinyint(4) NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`respective_steward` int(11) NULL  , 
	`split_id` varchar(200) COLLATE latin1_swedish_ci NULL  , 
	`unique_notifi_name` varchar(200) COLLATE latin1_swedish_ci NULL  , 
	`tag` varchar(200) COLLATE latin1_swedish_ci NULL  , 
	`count` int(11) NOT NULL  , 
	`status` tinyint(4) NOT NULL  , 
	`task_completed` tinyint(4) NOT NULL  , 
	`stop` tinyint(4) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_order_items_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`sale_id` int(11) unsigned NOT NULL  , 
	`item_status` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`kitchen_id` bigint(20) NOT NULL  , 
	`kitchen_type_id` bigint(20) NOT NULL  , 
	`recipe_id` int(11) unsigned NOT NULL  , 
	`recipe_code` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`option_id` int(11) NULL  , 
	`addon_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`addon_qty` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`buy_id` bigint(20) NOT NULL  , 
	`buy_quantity` bigint(20) NOT NULL  , 
	`get_item` bigint(20) NOT NULL  , 
	`get_quantity` bigint(20) NOT NULL  , 
	`total_get_quantity` bigint(20) NOT NULL  , 
	`net_unit_price` decimal(25,6) NOT NULL  , 
	`unit_price` decimal(25,6) NULL  , 
	`quantity` bigint(20) NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`order_item_cancel_id` tinyint(4) NOT NULL  COMMENT 'order cancelled update used id' , 
	`order_item_cancel_status` tinyint(1) NOT NULL  COMMENT '1->cancelled,0->not cancelled' , 
	`order_item_cancel_note` varchar(250) COLLATE utf8_general_ci NOT NULL  , 
	`item_tax` decimal(25,6) NULL  , 
	`tax_rate_id` int(11) NULL  , 
	`tax` varchar(55) COLLATE utf8_general_ci NULL  , 
	`discount` varchar(55) COLLATE utf8_general_ci NULL  , 
	`item_discount` decimal(25,6) NULL  , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`subtotal` decimal(25,6) NOT NULL  , 
	`serial_no` varchar(255) COLLATE utf8_general_ci NULL  , 
	`real_unit_price` decimal(25,6) NULL  , 
	`sale_item_id` int(11) NULL  , 
	`recipe_unit_id` int(11) NULL  , 
	`recipe_unit_code` varchar(10) COLLATE utf8_general_ci NULL  , 
	`unit_quantity` decimal(15,6) NOT NULL  , 
	`comment` varchar(255) COLLATE utf8_general_ci NULL  , 
	`comment_price` decimal(10,2) NOT NULL  , 
	`gst` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`time_started` datetime NOT NULL  , 
	`time_end` datetime NOT NULL  , 
	`escalation_one_time` datetime NOT NULL  , 
	`escalation_two_time` datetime NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`variant` varchar(200) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_variant_id` tinyint(4) NOT NULL  , 
	`stock_out_data` text COLLATE utf8_general_ci NOT NULL  , 
	`image_path` text COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name_img` text COLLATE utf8_general_ci NOT NULL  , 
	`addon_name_img` text COLLATE utf8_general_ci NOT NULL  , 
	`unwanted_ingredients` varchar(100) COLLATE utf8_general_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_orders_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`order_type` tinyint(4) NOT NULL  , 
	`customer_request` tinyint(4) NOT NULL  , 
	`table_id` bigint(20) NOT NULL  , 
	`seats_id` bigint(20) NOT NULL  , 
	`split_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`order_status` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`order_from` enum('web','app') COLLATE utf8_general_ci NOT NULL  , 
	`date` datetime NOT NULL  COMMENT 'transaction date' , 
	`created_on` datetime NOT NULL  , 
	`reference_no` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`customer` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`biller_id` int(11) NOT NULL  , 
	`biller` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`total` decimal(25,6) NOT NULL  , 
	`recipe_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`order_discount_id` varchar(20) COLLATE utf8_general_ci NULL  , 
	`total_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`recipe_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_tax_id` int(11) NULL  , 
	`order_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`total_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`shipping` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`grand_total` decimal(25,6) NOT NULL  , 
	`sale_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_term` tinyint(4) NULL  , 
	`due_date` date NULL  , 
	`order_cancel_id` tinyint(4) NOT NULL  COMMENT 'order cancelled update used id' , 
	`order_cancel_status` tinyint(1) NOT NULL  COMMENT '1->cancelled,0->not cancelled' , 
	`order_cancel_note` varchar(250) COLLATE utf8_general_ci NOT NULL  , 
	`created_by` int(11) NULL  , 
	`updated_by` int(11) NULL  , 
	`updated_at` timestamp NULL  , 
	`total_items` smallint(6) NULL  , 
	`pos` tinyint(1) NOT NULL  DEFAULT 0 , 
	`paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`return_id` int(11) NULL  , 
	`surcharge` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`return_sale_ref` varchar(55) COLLATE utf8_general_ci NULL  , 
	`sale_id` int(11) NULL  , 
	`return_sale_total` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`rounding` decimal(10,6) NULL  , 
	`suspend_note` varchar(255) COLLATE utf8_general_ci NULL  , 
	`api` tinyint(1) NULL  DEFAULT 0 , 
	`shop` tinyint(1) NULL  DEFAULT 0 , 
	`address_id` int(11) NULL  , 
	`reserve_id` int(11) NULL  , 
	`hash` varchar(255) COLLATE utf8_general_ci NULL  , 
	`manual_payment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`table_whitelisted` tinyint(4) NOT NULL  , 
	`ordered_by` enum('steward','customer') COLLATE utf8_general_ci NOT NULL  , 
	`waiter_id` tinyint(4) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_payments_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`action` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`date` datetime NULL  , 
	`paid_on` datetime NOT NULL  , 
	`sale_id` int(11) NULL  , 
	`bill_id` int(11) NOT NULL  , 
	`return_id` int(11) NULL  , 
	`purchase_id` int(11) NULL  , 
	`reference_no` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`transaction_id` varchar(50) COLLATE utf8_general_ci NULL  , 
	`paid_by` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`cheque_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_holder` varchar(25) COLLATE utf8_general_ci NULL  , 
	`cc_month` varchar(2) COLLATE utf8_general_ci NULL  , 
	`cc_year` varchar(4) COLLATE utf8_general_ci NULL  , 
	`cc_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`amount` decimal(25,6) NOT NULL  , 
	`amount_exchange` decimal(25,6) NOT NULL  , 
	`currency` varchar(3) COLLATE utf8_general_ci NULL  , 
	`created_by` int(11) NOT NULL  , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`note` text COLLATE utf8_general_ci NOT NULL  , 
	`type` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`sale_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` text COLLATE utf8_general_ci NOT NULL  , 
	`payment_note` text COLLATE utf8_general_ci NOT NULL  , 
	`pos_paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`pos_balance` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`approval_code` varchar(50) COLLATE utf8_general_ci NULL  , 
	`customer_payment_type` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`warehouse_id` tinyint(4) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_restaurant_table_orders_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`order_id` int(11) NOT NULL  , 
	`table_id` int(11) NOT NULL  , 
	`session_id` int(11) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_restaurant_table_sessions_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`order_id` int(11) NOT NULL  , 
	`table_id` int(11) NOT NULL  , 
	`session_started` datetime NOT NULL  , 
	`session_end` datetime NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`split_id` varchar(255) COLLATE latin1_swedish_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_rough_tender_payments_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`action` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`date` datetime NULL  , 
	`paid_on` datetime NOT NULL  , 
	`sale_id` int(11) NULL  , 
	`bill_id` int(11) NOT NULL  , 
	`return_id` int(11) NULL  , 
	`purchase_id` int(11) NULL  , 
	`reference_no` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`transaction_id` varchar(50) COLLATE utf8_general_ci NULL  , 
	`paid_by` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`cheque_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_no` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cc_holder` varchar(25) COLLATE utf8_general_ci NULL  , 
	`cc_month` varchar(2) COLLATE utf8_general_ci NULL  , 
	`cc_year` varchar(4) COLLATE utf8_general_ci NULL  , 
	`cc_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`amount` decimal(25,6) NOT NULL  , 
	`amount_exchange` decimal(25,6) NOT NULL  , 
	`currency` varchar(3) COLLATE utf8_general_ci NULL  , 
	`created_by` int(11) NOT NULL  , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`note` text COLLATE utf8_general_ci NOT NULL  , 
	`type` varchar(20) COLLATE utf8_general_ci NOT NULL  , 
	`sale_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` text COLLATE utf8_general_ci NOT NULL  , 
	`payment_note` text COLLATE utf8_general_ci NOT NULL  , 
	`pos_paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`pos_balance` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`approval_code` varchar(50) COLLATE utf8_general_ci NULL  , 
	`customer_payment_type` varchar(100) COLLATE utf8_general_ci NOT NULL  , 
	`bill_settled` tinyint(4) NOT NULL  COMMENT '0-No, 1-yes' , 
	`loyalty_points` int(11) NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_rough_tender_sale_currency_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`sale_id` bigint(20) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`currency_id` int(11) NOT NULL  , 
	`currency_rate` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`paid_type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`amount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`created_on` date NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_sale_currency_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`sale_id` bigint(20) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`currency_id` int(11) NOT NULL  , 
	`currency_rate` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`paid_type` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`amount` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`created_on` date NOT NULL  , 
	`warehouse_id` tinyint(4) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_sale_items_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`sale_id` int(11) unsigned NOT NULL  , 
	`bil_type` tinyint(4) NOT NULL  , 
	`bil_id` bigint(20) NOT NULL  , 
	`recipe_id` int(11) unsigned NOT NULL  , 
	`recipe_code` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_name` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_type` varchar(20) COLLATE utf8_general_ci NULL  , 
	`item_status` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`option_id` int(11) NULL  , 
	`addon_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`addon_qty` varchar(50) COLLATE utf8_general_ci NOT NULL  , 
	`net_unit_price` decimal(25,6) NOT NULL  , 
	`unit_price` decimal(25,6) NULL  , 
	`quantity` bigint(20) NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`item_tax` decimal(25,6) NULL  , 
	`tax_rate_id` int(11) NULL  , 
	`tax` varchar(55) COLLATE utf8_general_ci NULL  , 
	`discount` varchar(55) COLLATE utf8_general_ci NULL  , 
	`item_discount` decimal(25,6) NULL  , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`subtotal` decimal(25,6) NOT NULL  , 
	`serial_no` varchar(255) COLLATE utf8_general_ci NULL  , 
	`real_unit_price` decimal(25,6) NULL  , 
	`sale_item_id` int(11) NULL  , 
	`recipe_unit_id` int(11) NULL  , 
	`recipe_unit_code` varchar(10) COLLATE utf8_general_ci NULL  , 
	`unit_quantity` decimal(15,6) NOT NULL  , 
	`comment` varchar(255) COLLATE utf8_general_ci NULL  , 
	`comment_price` decimal(10,2) NOT NULL  , 
	`gst` varchar(20) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`recipe_variant_id` tinyint(4) NOT NULL  , 
	`variant` varchar(4) COLLATE utf8_general_ci NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';



CREATE TABLE `srampos_sale_return_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`sale_id` bigint(20) NOT NULL  , 
	`order_id` bigint(20) NOT NULL  , 
	`split_id` varchar(255) COLLATE latin1_swedish_ci NOT NULL  , 
	`order_type` bigint(20) NOT NULL  , 
	`created_by` bigint(20) NOT NULL  , 
	`created_at` datetime NOT NULL  , 
	`confirmed_by` int(11) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';


CREATE TABLE `srampos_sales_archival`(
	`id` int(11) NOT NULL  DEFAULT 0 , 
	`bilgenerator_type` tinyint(4) NOT NULL  COMMENT '0-POS, 1-CUSTOMER' , 
	`consolidated` tinyint(4) NOT NULL  , 
	`sales_type_id` tinyint(4) NOT NULL  , 
	`sales_split_id` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`sales_table_id` bigint(20) NOT NULL  , 
	`date` datetime NOT NULL  , 
	`created_on` datetime NOT NULL  , 
	`reference_no` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`delivery_person_id` bigint(20) NOT NULL  , 
	`customer_id` int(11) NOT NULL  , 
	`customer` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`biller_id` int(11) NOT NULL  , 
	`biller` varchar(55) COLLATE utf8_general_ci NOT NULL  , 
	`warehouse_id` int(11) NULL  , 
	`note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`staff_note` varchar(1000) COLLATE utf8_general_ci NULL  , 
	`total` decimal(25,6) NOT NULL  , 
	`recipe_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_discount_id` varchar(20) COLLATE utf8_general_ci NULL  , 
	`total_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_discount` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`manual_item_discount` decimal(25,2) NOT NULL  , 
	`manual_item_discount_val` varchar(10) COLLATE utf8_general_ci NOT NULL  , 
	`recipe_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`order_tax_id` int(11) NULL  , 
	`order_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`total_tax` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`shipping` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`grand_total` decimal(25,6) NOT NULL  , 
	`sale_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_status` varchar(20) COLLATE utf8_general_ci NULL  , 
	`payment_term` tinyint(4) NULL  , 
	`due_date` date NULL  , 
	`created_by` int(11) NULL  , 
	`updated_by` int(11) NULL  , 
	`updated_at` timestamp NULL  , 
	`total_items` smallint(6) NULL  , 
	`pos` tinyint(1) NOT NULL  DEFAULT 0 , 
	`paid` decimal(25,6) NULL  DEFAULT 0.000000 , 
	`return_id` int(11) NULL  , 
	`surcharge` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`attachment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`return_sale_ref` varchar(55) COLLATE utf8_general_ci NULL  , 
	`cancel_status` tinyint(4) NULL  DEFAULT 0 COMMENT '0->not cancel,1->cancel' , 
	`cancel_remarks` text COLLATE utf8_general_ci NOT NULL  , 
	`canceled_user_id` tinyint(4) NOT NULL  , 
	`return_sale_total` decimal(25,6) NOT NULL  DEFAULT 0.000000 , 
	`rounding` decimal(10,6) NULL  , 
	`suspend_note` varchar(255) COLLATE utf8_general_ci NULL  , 
	`api` tinyint(1) NULL  DEFAULT 0 , 
	`shop` tinyint(1) NULL  DEFAULT 0 , 
	`address_id` int(11) NULL  , 
	`reserve_id` int(11) NULL  , 
	`hash` varchar(255) COLLATE utf8_general_ci NULL  , 
	`manual_payment` varchar(55) COLLATE utf8_general_ci NULL  , 
	`cgst` decimal(25,6) NULL  , 
	`sgst` decimal(25,6) NULL  , 
	`igst` decimal(25,6) NULL  , 
	`default_currency_code` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`default_currency_rate` varchar(255) COLLATE utf8_general_ci NOT NULL  , 
	`table_whitelisted` tinyint(1) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET='latin1' COLLATE='latin1_swedish_ci';

CREATE TABLE `srampos_kitchen_orders_archival` (
  `id` int(11) NOT NULL DEFAULT '0',
  `sale_id` bigint(20) NOT NULL,
  `waiter_id` bigint(20) NOT NULL,
  `chef_id` bigint(20) NOT NULL,
  `status` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `srampos_settings` 

	/*ADD COLUMN `archival` tinyint(4)   NULL DEFAULT 0 after `allow_reg` , 
	ADD COLUMN `archival_days` int(11)   NULL DEFAULT 0 after `archival` ;*/
	ADD COLUMN `archival` tinyint(4)   NULL DEFAULT 0 after `allow_reg` ;
	ALTER TABLE `srampos_settings` ADD `archival_days` INT NOT NULL DEFAULT '1' AFTER `bbq_notify_no_of_times`;
	ALTER TABLE `srampos_last_archival_process` CHANGE `status` `status` VARCHAR(50) NULL DEFAULT NULL;
	
	
insert  into `srampos_archival_tables`(`id`,`archival_from_table`,`archival_to_table`,`active`) values 
(1,'srampos_restaurant_table_orders','srampos_restaurant_table_orders_archival',1),
(2,'srampos_kitchen_orders','srampos_kitchen_orders_archival',1),
(3,'srampos_restaurant_table_sessions','srampos_restaurant_table_sessions_archival',1),
(4,'srampos_bils','srampos_bils_archival',1),
(5,'srampos_bil_items','srampos_bil_items_archival',1),
(6,'srampos_addon_bill_items','srampos_addon_bill_items_archival',1),
(7,'srampos_orders','srampos_orders_archival',1),
(8,'srampos_order_items','srampos_order_items_archival',1),
(9,'srampos_sales','srampos_sales_archival',1),
(10,'srampos_sale_items','srampos_sale_items_archival',1),
(11,'srampos_addon_sale_items','srampos_addon_sale_items_archival',1),
(12,'srampos_sale_currency','srampos_sale_currency_archival',1),
(13,'srampos_payments','srampos_payments_archival',1),
(14,'srampos_bbq','srampos_bbq_archival',1),
(15,'srampos_bbq_bil_items','srampos_bbq_bil_items_archival',1),
(16,'srampos_rough_tender_sale_currency','srampos_rough_tender_sale_currency_archival',1),
(17,'srampos_rough_tender_payments','srampos_rough_tender_payments_archival',1),
(18,'srampos_archive_restaurant_table_orders','srampos_archive_restaurant_table_orders_archival',1),
(19,'srampos_archive_kitchen_orders','srampos_archive_kitchen_orders_archival',1),
(20,'srampos_archive_restaurant_table_sessions','srampos_archive_restaurant_table_sessions_archival',1),
(21,'srampos_archive_bils','srampos_archive_bils_archival',1),
(22,'srampos_archive_bil_items','srampos_archive_bil_items_archival',1),
(23,'srampos_archive_orders','srampos_archive_orders_archival',1),
(24,'srampos_archive_order_items','srampos_archive_order_items_archival',1),
(25,'srampos_archive_sales','srampos_archive_sales_archival',1),
(26,'srampos_archive_sale_items','srampos_archive_sale_items_archival',1),
(27,'srampos_archive_sale_currency','srampos_archive_sale_currency_archival',1),
(28,'srampos_archive_payments','srampos_archive_payments_archival',1),
(29,'srampos_archive_bbq','srampos_archive_bbq_archival',1),
(30,'srampos_archive_bbq_bil_items','srampos_archive_bbq_bil_items_archival',1),
(31,'srampos_sale_return','srampos_sale_return_archival',1),
(32,'srampos_notiy','srampos_notiy_archival',1),
(33,'srampos_archive_rough_tender_sale_currency','srampos_archive_rough_tender_sale_currency_archival',1),
(34,'srampos_archive_rough_tender_payments','srampos_archive_rough_tender_payments_archival',1);

